# -*- coding: utf-8 -*-
"""EDA_Survey_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xSEJTtuSwU1YzDmLRpV2axMq5ppvdzll
"""

import pandas as pd
import os

# Path to the CSV file
survey_path = PATHS["data_raw"] + "Survey/BaselineData_V6_melusi.csv"

# Check if the file exists
if os.path.exists(survey_path):
    print("File exists ✅")
else:
    print("File not found ❌")

# Read the CSV with semicolon separator and correct encoding
df = pd.read_csv(survey_path, sep=';', encoding='latin1')

# Display basic summary
print("Shape of dataset:", df.shape)
print("\nColumns:\n", df.columns)
print("\nData types:\n", df.dtypes)
print("\nFirst 5 rows:\n", df.head())
print("\nSummary statistics for numeric columns:\n", df.describe())
print("\nMissing values per column:\n", df.isnull().sum())