# -*- coding: utf-8 -*-
"""EDA_Survey_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xSEJTtuSwU1YzDmLRpV2axMq5ppvdzll
"""

import pandas as pd
import os

# Path to the CSV file
survey_path = PATHS["data_raw"] + "Survey/DataBaseline_v2.csv"

# Check if the file exists
if os.path.exists(survey_path):
    print("File exists ✅")
else:
    print("File not found ❌")

# Read the CSV with semicolon separator and correct encoding
df = pd.read_csv(survey_path, sep=';', encoding='latin1')
df = df[df['sites'] == "Melusi"]

# Display basic summary
print("Shape of dataset:", df.shape)
print("\nColumns:\n", df.columns)
print("\nData types:\n", df.dtypes)
print("\nFirst 5 rows:\n", df.head())
print("\nSummary statistics for numeric columns:\n", df.describe())
print("\nMissing values per column:\n", df.isnull().sum())

#Some statistics that can be helpful:
resident_population_df = df[df['is_member_resident'] == "Yes, resident"]
population = resident_population_df["hhr_member_total"].sum()
population_total = df["hhr_member_total"].sum() 
print("Estimated resident population:", int(population))
print("Estimated non-resident + resident  population:", int(population_total))
dwelling_total = df.shape[0]
print("Estimated number of dwellings:", int(dwelling_total))
# Count the number of unique blocks
num_unique_blocks = df['Blocks'].nunique()
print("Number of unique blocks:", num_unique_blocks)
num_unique_Longitude_coords = df['Longitude'].nunique()
print("Number of unique Longitude_coords:", num_unique_Longitude_coords)
num_unique_Latitude_coords = df['Latitude'].nunique()
print("Number of unique Latitude_coords:", num_unique_Latitude_coords)

#Checking if all rows are unique:
# Count duplicate rows in the entire DataFrame
num_duplicates = df.duplicated().sum()
print("Number of duplicate rows:", num_duplicates)

# If you want to actually see the duplicate rows
duplicate_rows = df[df.duplicated()]
print("Duplicate rows:")
print(duplicate_rows)

#checking the unique values for each column:
unique_counts = df.nunique()
unique_counts
