# -*- coding: utf-8 -*-
"""Plot The GeoTIFF image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gq0dP1BJplUm8xxFT2Lg9g2dLY5i6wJz
"""

from google.colab import userdata
TOKEN = userdata.get('MIT808_secret')
EMAIL = userdata.get('EMAIL')
Password = userdata.get('Password')
username = userdata.get('Username')
repo = "melusi-2025"

!git config --global user.name username
!git config --global user.email EMAIL
!git config --global user.password Password

folder_name = repo
import shutil, os

if os.path.exists(folder_name):
    shutil.rmtree(folder_name)
    print(f"Deleted existing folder: {folder_name}")
else:
    print(f"No existing folder named {folder_name}")
    print(f"Cloning folder named {folder_name}")
    !git clone https://{username}:{TOKEN}@github.com/MrChanda/melusi-2025.git

from google.colab import drive
drive.mount('/content/drive')

import sys
import importlib.util
from pathlib import Path

# Path to your local setup.py
setup_path = "/content/melusi-2025/src/setup.py"

# Load it as a module with a unique name
spec = importlib.util.spec_from_file_location("melusi_setup", setup_path)
melusi_setup = importlib.util.module_from_spec(spec)
sys.modules["melusi_setup"] = melusi_setup
spec.loader.exec_module(melusi_setup)

# Now you can call your functions safely
melusi_setup.configure_environment()

import rasterio
from rasterio.enums import Resampling
import matplotlib.pyplot as plt

from rasterio.enums import Resampling
import matplotlib.pyplot as plt
tif_path = melusi_setup.PATHS['geotiff']
with rasterio.open(tif_path) as src:
    img = src.read(
        out_shape=(
            src.count,
            src.height // 3,
            src.width // 3
        ),
        resampling=Resampling.bilinear
    )

img = img.transpose((1,2,0))

plt.figure(figsize=(10,10))
plt.imshow(img)
plt.axis("off")
plt.title("Melusi Preview")
plt.show()